name: Spark

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d --build

      - run: |
          docker-compose exec -T spark which pyspark
          docker-compose exec -T spark pyspark -c "sc._gateway.jvm.org.apache.hadoop.util.VersionInfo.getVersion()"
 
      - name: Stop containers
        if: always()
        run: docker-compose down