name: Spark

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d --build

      - run: |
          docker-compose exec -T spark python3 /app/scripts/hadoopVersion.py
          docker-compose exec -T spark python3 /app/scripts/pysparkTest.py
 
      - name: Stop containers
        if: always()
        run: docker-compose down