name: Spark

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d --build

      - run: |
          docker-compose exec spark which pyspark
          docker-compose exec spark pyspark -c " import os; print(spark)"

      - name: Stop containers
        if: always()
        run: docker-compose down
